name: Check PR can be merged
on:
  pull_request:
    types: [labeled]
jobs:
  Run Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.2
        with:
          # The label name to automatically merge. Default is "automerge".
          label-name: lgtm
          # The number of reviewers to automatically merge. Default is 1.
          reviewers-number: 1
          # The merge method ("merge", "squash", "rebase"). Default is "merge"
          merge-method: merge
          # Let the bot delete the merged branch. true or false.
          auto-delete: true
          # GitHub WebHook Secret Token
          github-token: ${{ secrets.CHILLY_BOT_TOKEN }}
